# Requires installation of ansible. Make remote version?
- name: Spin up server core
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: Setup normal user with sudo / admin access
    user:
      name: ubuntu
      groups: adm,sudo
    tags:
    - system
    - users
    - admin_user

  - name: Setup service user (including additional groups if applicable)
    user:
      name: "{{ service_user | default('svc_user') }}"
      groups: "{{ service_user_groups | default(omit) }}"
      create_home: false
      system: true
    tags:
    - system
    - containers
    - users
    - service_user

  - name: Upgrade existing system
    apt:
      update_cache: true
      upgrade: true
    tags:
    - system
    - containers

  - name: Install tools
    apt:
      name:
      - nano # Everyone needs a sensible editor!
      - podman-docker
    tags:
    - system
    - containers

  - name: Prepare core directories
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ service_user | default('svc_user') }}"
      group: "{{ service_group | default(omit) }}"
      mode: 0775
    loop:
    - /srv/portainer
    - /srv/syncthing
    - /srv/syncthing/stfolder
    tags:
    - system
    - containers
    - filesystem

  - name: Create Syncthing 'stignore' file (if it doesn't exist)
    copy:
      content: ""
      dest: /srv/syncthing/stignore
      force: false
      owner: "{{ service_user | default('svc_user') }}"
      group: "{{ service_group | default(omit) }}"
      mode: 0644
    tags:
    - system
    - containers
    - filesystem

  - name: Spin up Portainer and Syncthing # TODO: Rootless operation
    community.docker.docker_compose:
      project_name: server_core
      project_src: docker_compose
      files:
      - server_core.yml
    tags:
    - system
    - containers
    - server_core
